manifestVersion = 0

[package]
  type = "mod"
  name = "miners-horizon"
  description = "Adds in a dimension specifically for mining."
  version = "1.6.0"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = ""
  fabric = "*"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"
